### PR TITLE
Add explanations & unlisted game support

### PR DESCRIPTION
**Pull request by hamishivi**
Alright, so this adds explanations to the recommendations generated. From personal testing, I'm not convinced the explanations actually explain anything useful, but hey, give it a shot. It also makes things slower, since 4 explanations per game = ~40 api lookups (for the names), meaning that just loading the recommendation call takes like 50 api calls. This is *not* ideal in the slightest (especially since api call rate limits are a thing).

I also snuck in a call to an api that lists unlisted steam games (https://steam-tracker.com/), and then checks if we can't find a game on steam to see if it's there. Note this won't cover everything, since there are steamapps without any sort of name or anything, but it's better than nothing.

I also cleaned up and removed some stuff that we didn't need anymore, and added a new shrek.

### CODE REVIEW

**Comment by KittenHero** [comment]
4 explanations per game = ~40 api lookups
but wouldn't there be a lot of overlapping games in the explanation in practice, so you could do some caching

**Comment by hamishivi** [comment]
I added caching on everything with a little wrapper around requests :)

**Comment by KittenHero** [comment]
if you only display game name for explanations
it might be a good idea to pass flags to get_game_info to not load unnecessary resources

**Comment by hamishivi** [comment]
@KittenHero Yeah, I want to rewrite/refactor a fair bit (you've beat me to some parts) so it's easier to make optimizations like that, so I'm just gonna leave this PR open until that gets done.

**Comment by hamishivi** [comment]
@KittenHero I kinda wanted to rewrite the '/' route in views.py, but I reckon it should wait until your extra thread stuff. Do you reckon I should just merge now? Any other parts you reckon could be improved in this PR? (I feel like the cache should be a class but that would require some rewriting and changing how some of the code works, especially with regards to dependencies).

**Comment by KittenHero** [comment]
I don't know what you're talking about

**Comment by hamishivi** [comment]
Code you reckon could be written better or something along those lines before I merge the PR

**Pull request merged**
